name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build & Sign
      run: |
        # Build the program
        echo "echo 'Hello world 👋'" > program.sh
        # Sign the program
        echo "${{ secrets.private_signing_key }}" > private_key.pem
        openssl dgst -sha256 -sign private_key.pem -out signature.sig program.sh
    - name: Publish
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.release_token }}
        files: |
          program.sh
          signature.sig
          public_key.pem
